### ISSUE TITLE
[BUG] Nitro gift button toggle not working

### ISSUE THREAD

**Issue by jh34ghu43gu** [LancersBucket/plugin-RemoveChatButtons#4]
Nitro gift toggle not working for me on version 1.7.0
BD version Core 1.10.2
Discord Stable 342968
Windows 10

**Comment by samiscoolest** [comment]
also experiencing this

**Comment by MisansProducts** [comment]
Same

**Comment by LancersBucket** [comment]
Fixed in 1.7.1

**Comment by jh34ghu43gu** [comment]
> Fixed in 1.7.1

You forgot to update the version number fyi

**Comment by LancersBucket** [comment]
> > Fixed in 1.7.1
> 
> You forgot to update the version number fyi

Totally right, I updated it in the changelog but not the actual script. Just pushed a fix right now.
